version: '3.3'
services:
  app:
    container_name: ivr-backend
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: always
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'accubits_ivr'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  docs:
    image: accubits/api-doc-auto-generator:latest
    ports:
      - ${DOCS_PORT:-4567}:4567
    volumes:
      - ./output.md:/usr/src/app/source/index.html.md
volumes: 
  node_modules: 
  my-db: